[package]
name = "rust-lamp"
version = "0.1.0"
authors = ["Amit Sarangi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window="0.93.0"
rand="0.6.5"
